title: DOMO wiki
description: This is the official DOMO Wiki
show_downloads: true
git_branch: master
logo_url: https://github.com/Utopianer/DOMO-Project/tree/master/docs/wiki/assets/images/logo.png
google_analytics:
theme: 
wiki_folder: wiki
use_github_wiki: false
use_prose_io: true
google_cse_token: 
custom_head: false
custom_sidebar: false
custom_footer: false
gems:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed
sass:
  sass_dir: _sass