title: DOMO wiki
description: This is the official DOMO Wiki
show_downloads: true
git_branch: master
logo_url:logo.png
google_analytics:
theme: 
wiki_folder: wiki
use_github_wiki: false
use_prose_io: true
google_cse_token: 
custom_head: true
custom_sidebar: true
custom_footer: true
gems:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed
