url: https://domoproject.me
baseurl:

# Site settings
title: The DOMO Project
email: domocoin@gmx.net
description: "Building a decentralized Community. Domocoin is a cryptocurrency used as a ticket to join the social network of the future (Proof of Ownership)"


# Social Networks
networks:
- name: Twitter
  pic: 1
  url: https://twitter.com/domocoin

- name: Discord
  pic: 2
  url: https://discordapp.com/invite/VuTYQhK

- name: Telegram
  pic: 3
  url:  https://t.me/DOMOproject

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

  - title: envelope
    url: mailto:admin@domo.network

# Build settings
markdown: kramdown
permalink: pretty
